### ISSUE TITLE
Include default buildflags set in flatpak-builder

### ISSUE THREAD

**Issue by Erick555** [flatpak/flatpak-builder#146]
This will allow for unification of package building and set common standards for it. See https://github.com/flathub/flathub/issues/319#issuecomment-386808469 and https://github.com/flathub/flathub/issues/353 for more info.

I propose following default flags to be used for building common apps:
```
"cflags": "-O2 -g -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2", 
"cxxflags": "-O2 -g -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2",
"ldflags": "-fstack-protector-strong -Wl,-z,relro,-z,now",
```
I know there is an [effort](https://github.com/flatpak/flatpak-builder/pull/142) to set default flags in runtime but [IMO it's still inferior solution](https://github.com/flathub/flathub/issues/319#issuecomment-386811154).

**Comment by TingPing** [comment]
I think `flatpak-builder` should be as unopinionated in flags as possible and the SDK defining flags as that PR does is the best solution.

**Comment by TingPing** [comment]
I think you are overselling how many runtimes we currently have. Depending on the implementaiton this can be set in a single place right now, the freedesktop runtime. And it avoids potential issues in the future where other runtimes have other needs without over complicating anything.

**Comment by Erick555** [comment]
Then why setting it in freedesktop runtime rather than flatpak-builder? Why do you think the former is better than the latter? It could be overridden with other runtimes flags when needed in the same way. I would happy to read some arguments against setting it in flatpak-builder once and for all.

All major distros like Fedora, Ubuntu, Debian, Gentoo, OpenSuse, Archlinux are setting common buildflags globally which worked well for decades. Flatpak started without setting default buildflags, allowing apps to set their own and now will allow runtime(s) to set their own. I believe it will end up with global buildflags as everyone else sooner or later but sooner is better.

**Comment by alexlarsson** [comment]
We're working on sdk defaults in https://github.com/flatpak/flatpak-builder/pull/142

It makes no sense to enforce a specific set of flags in flatpak-builder, which is unaware of what compiler and security features are available in the sdk. For example, there is no guarantee that -fstack-protector-strong works in a particular runtime (in fact, it probably doesn't work in some of the older ones we have, although nothing really uses them anymore). Additionally we can't ever modify defaults in flatpak-builder because that may cause older manifests to stop building, while we can tweak the default in new versions of the SDKs.
