### ISSUE TITLE
rename-desktop-file leaves launchable entry in appdata unchanged

### ISSUE THREAD

**Issue by Alexander-Wilms** [flatpak/flatpak-builder#155]
`<launchable type="desktop-id">texstudio.desktop</launchable>`
doesn't get changed to
`<launchable type="desktop-id">org.texstudio.TeXstudio.desktop</launchable>`
when having `rename-desktop-file: texstudio.desktop` in the manifest.

Cf. https://github.com/flathub/org.texstudio.TeXstudio/issues/2

**Comment by Jehan** [comment]
So for the record, we had the issue at GIMP for a long time until we finally understood it (thanks to @hughsie!). We are now patching our appdata for flatpak only so the bug is worked around for now, but it would be nice to be fixed at some point.
See: https://github.com/flathub/org.gimp.GIMP/issues/8
