### ISSUE TITLE
Not installed extension silently ignored in "add-extensions"

### ISSUE THREAD

**Issue by plata** [flatpak/flatpak-builder#223]
For example:
```JSON
  "add-extensions": {
    "org.freedesktop.Platform.this-does-not-exist": {
      "directory": "lib/somewhat",
      "version": "18.08"
    }
  },
```

I would expect that flatpak-builder aborts with an error.

**Comment by TingPing** [comment]
You are just defining a new extension point, so ofc it doesn't need to exist.

**Comment by kirbyfan64** [comment]
Would it be worth it to have a concept of "required extensions"? Since they're also used for e.g. Compat.i386.

**Comment by TingPing** [comment]
The entire point of extensions is they are optional. If extensions start being not-optional then I think that warrants a different solution.

**Comment by alexlarsson** [comment]
It is possible to require that some runtime (sdk) extensions be installed during *build* by using the sdk-extensions key. For instance you can require an extension with a rust compiler if that is not in the normal sdk. 

However, this is an additional layer in flatpak-builder, flatpak itself does not have non-optional dependencies. This is a design decision, because we're not making a packaging system like deb/rpm. The moment you do that you run into all the issues with those that we're trying to fix.

**Comment by plata** [comment]
So Compat.i386 should be used as sdk-extension? Compat.i386 is in fact what I wanted to use.

Apart from that: I can somehow understand that you do not want to fail the build but couldn't there be at least a warning?

**Comment by plata** [comment]
Got it. I'm not that familiar with flatpak so sorry for asking stupid questions. Would be nice to have an idiomatic solution for this issue described in the docs.

**Comment by aiamuzz** [comment]
> However, I don't think we ensure such extensions are installed, nor do we install them with
> --install-deps-from=REMOTE. Maybe we should do that.

@alexlarsson ... @TingPing ... until this decision is made ...

Can an **additional note** be part of the app description on the flathub website application page ?

Also if you could have an additional command added along with the application install command at the bottom of that page under the installation instructions ... i think the user will avoid scratching their heads and looking lost ?

`flatpak install flathub org.phoenicis.playonlinux 
flatpak install flathub org.freedesktop.Platform.Compat.i386`
