### ISSUE TITLE
Cannot `run-tests` with `--sandbox`

### ISSUE THREAD

**Issue by TingPing** [flatpak/flatpak-builder#229]
I'm not sure why this is limited but it is a pretty big restriction that doesn't make sense to me.

**Comment by alexlarsson** [comment]
I don't think it is disallowed. specifying test-args is, but that is just how you would get --share=network into the tests for instance, which obviously isn't compatible with sandboxing.

**Comment by TingPing** [comment]
A the time (its been a year..) it errored out-right.

**Comment by Unrud** [comment]
> I don't think it is disallowed.

@alexlarsson It's a bug:

https://github.com/flatpak/flatpak-builder/blob/ae29d867a49efaee8b6e888c5650ea8b08f94058/src/builder-options.c#L1206-L1207

https://github.com/flatpak/flatpak-builder/blob/ae29d867a49efaee8b6e888c5650ea8b08f94058/src/builder-options.c#L1220-L1224

`array->len > 0` is always true because the array  always contains at least the `--readonly` argument.
