### ISSUE TITLE
flatpak-builder: --device can be more specific

### ISSUE THREAD

**Issue by marcosps** [flatpak/flatpak-builder#234]
When creating a new json manifest for my webcam app, I needed to add "--device=all" (other apps like Steam also do that).

In this case, should flatpak have more targets from --device, like --device=media (for webcams on /dev/videoX and radio devices for /dev/radioX) ?

Currently, only kvm, dri and all exists (https://github.com/flatpak/flatpak/blob/2a661fd448a153992e07904b666ef4fb748810a3/common/flatpak-run.c#L112)

If you guys agree, I can work on that.

**Comment by TingPing** [comment]
@matthiasclasen 	Uh, why would you transfer this here. Permissions are a `flatpak` issue. The fact `flatpak-builder` exposes them isn't relevant.

**Comment by matthiasclasen** [comment]
Because it had a flatpak-builder tag.

**Comment by hadess** [comment]
I'm going to close this because finer-grained permissions for static device sandbox holes aren't planned. There are plans for solving "joystick" (inputfd Wayland protocol), webcam (pipewire) and USB permissions. Most of those would be filed in xdg-desktop-portal's issues, as they would require new portals to be created.
