### ISSUE TITLE
RDNN: Why "Only last name segment can contain -"

### ISSUE THREAD

**Issue by phw** [flatpak/flatpak-builder#37]
Why is there a restrictions on the app ID "Only last name segment can contain -"? I tried to package https://github.com/parnold-x/nasc/ which uses the app ID `com.github.parnold-x.nasc`.

I don't really see the point here, as it is advised to use the reverse of an existing domain name, and that very well might contain `-` symbols.

**Comment by TingPing** [comment]
A recent answer:

```
<iamjsparber[m]> Hi everybody! Why does flatpak not allow dashes in the appid? Expecially because gnome does https://wiki.gnome.org/HowDoI/ChooseApplicationID 
<iamjsparber[m]> my app uses com.frac-tion.teleport
<alexlarsson> iamjsparber[m]: It is complicated. It used to not be allowed in dbus bus names (and is still not in dbus interface names), and flatpak app-ids are used as dbus ids
<alexlarsson> iamjsparber[m]: And its also due to security reasons in how exports work
<alexlarsson> iamjsparber[m]: it is allowed in the last element of the app-id though
<alexlarsson> iamjsparber[m]: i recommend using com.frac_tion.teleport
<alexlarsson> We want to allow exporting org.my.app-symbolic.png
<alexlarsson> So, exports must match the prefix like
<alexlarsson> org.my.app.*
<alexlarsson> or org.my.app[:invalid-char]*
<alexlarsson> we don't want an appid called org.my.app-foo.other.thing to be allowed to conflict with org.my.app
<alexlarsson> the exact rules have changed over time, trying to make it work as much as possible...
```

**Comment by smcv** [comment]
> it is advised to use the reverse of an existing domain name, and that very well might contain `-` symbols

D-Bus bus names (and hence freedesktop.org app IDs) also have the syntactic restriction that they can't contain a dot immediately followed by a digit. We can't change that in D-Bus without it being a compatibility break.

The transformation that I would recommend (for all reversed domain names, not just in Flatpak) is:

* replace `-` with `_`
* if a component starts with a digit, prepend `_` to it

This cannot result in a collision with other valid DNS domain names, because DNS domain name components aren't allowed to contain `_` or start with `-`, so there is no ambiguity.

7-zip.org is an example of a well-known open source project that runs into both issues. If they wanted to release a tool with an app ID, it would be something like `org._7_zip.Archiver`.

**Comment by phw** [comment]
Thanks a lot for the clarification. From my personal point of view we can close this, but maybe this should get documented somewhere?

**Comment by smcv** [comment]
> maybe this should get documented somewhere?

I'm going to propose a patch for the Desktop Entry Specification.

**Comment by smcv** [comment]
> I'm going to propose a patch for the Desktop Entry Specification.

https://bugs.freedesktop.org/show_bug.cgi?id=103216 in the Desktop Entry specification, https://bugs.freedesktop.org/show_bug.cgi?id=103914 in the D-Bus specification.

**Comment by her001** [comment]
May I ask about the details of this issue being closed? It looks to me as if the changes required to change this behavior have landed in the desktop entry and dbus specs, but there was no other explanation here since then, nor a commit which mentions this issue.

**Comment by mwleeds** [comment]
@her001 Flatpak already disallows app IDs with `-` in a non-last segment or a digit starting a segment, and that's documented at least in the docs for `flatpak_is_valid_name`. What more needs to be done on this issue?

**Comment by her001** [comment]
Your response is enough for me. Basically: It is staying this way, and is documented.
