### ISSUE TITLE
[Question] Sign the repo non-interactively

### ISSUE THREAD

**Issue by proletarius101** [flatpak/flatpak-builder#377]
It's usual that we need to build the flatpaks by the CI. And it's more realistic for independent devs (and hobbyists) to build their flatpaks by CI and store them statically rather than hosting a flat-manager instance. The boundary here is, although we can import the gpg key by `echo $GPG_PASSPHRASE | gpg --import $GPG_KEY -d 0`, we can't do similar things for `flatpak build-sign`. That means it prompts for the passphrase and there's no way to input the passphrase non-interactively

So my question is, is there any workaround to enter the passphrase non-interactively (given that the passphrase in `$GPG_PASSPHRASE`? If no, maybe we should somehow implement it?

**Comment by Jehan** [comment]
It would be nice (as discussed in flatpak/flatpak#573 indeed 🙂). Just note that the solution should not propose to use `$GPG_PASSPHRASE` on command line (i.e. we should avoid a `--gpg-passphrase` CLI option), because it would end up in process name which is just visible by too many users.

A proper average solution would be to have either the passphrase in a config file (with proper permission, i.e. not readable by other users) or in a given environment variable with a specific name (`$FLATPAK_BUILDER_GPG_PASSPHRASE` or whatever) which is read when needed.

**Comment by proletarius101** [comment]
So yes it's even possible now
````bash
# GPG noninteractive passphase
GPG_PASSPHRASE=`echo $GPG_PASSPHRASE | base64 --decode`
gpg --list-keys --with-keygrip # init gpg
echo "allow-preset-passphrase" >> ~/.gnupg/gpg-agent.conf
gpg-connect-agent reloadagent /bye
/usr/libexec/gpg-preset-passphrase -P $GPG_PASSPHRASE --preset $GPG_KEY_GREP
gpg --import --batch ${GPG_PRIVATE_KEY}
flatpak build-update-repo --generate-static-deltas repo/
flatpak build-sign --gpg-sign=${GPG_KEY_ID} repo/

````

**Comment by Jehan** [comment]
@proletarius101 Interesting tool this `gpg-preset-passphrase`. For security reasons, I would suggest not to use the `-P` option though, because then anyone with simple user access can get your passphrase by looking at the processus name. This makes the point of a passphrase near-useless.

You could instead add the passphrase in a file (with read permission to your user only), then `cat` this file contents into `gpg-preset-passphrase` stdin (as the man of this tool says that by default, the passphrase is read from stdin).

At least this way, your passphrase is never visible in process list. The only way to get access to it would be to be able to login to the same user (or get root access), but anyway if an attacker manages so far, you should consider the key as compromised anyway.

**Comment by proletarius101** [comment]
> You could instead add the passphrase in a file (with read permission to your user only), then `cat` this file contents into `gpg-preset-passphrase` stdin (as the man of this tool says that by default, the passphrase is read from stdin).

Yes that sounds more secure even in the CI environment. Thanks for the advice! Updated.
