### ISSUE TITLE
Extracts debug info from debug files?

### ISSUE THREAD

**Issue by gasinvein** [flatpak/flatpak-builder#429]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

1.2.0

### Flatpak version

1.12.1

### How to reproduce

1. Build some app with more than one module from which debug info is to be extracted
2. Inspect `files/lib/debug` directory in the builddir

### Expected Behavior

Each file in `bin/` and `lib/` has corresponding `file.debug` file in `lib/debug`; no `lib/debug/lib/debug` directory present.

### Actual Behavior

`lib/debug` directory has another `lib/debug` directory inside, with files like `file.debug.debug` inside the 2nd level directory. Nesting level seems to depend on the amount of modules.

### Additional Information

It seems like each time debuginfo is extracted from a module, debuginfo is extracted from debuginfos of all previous modules.
For example, builddir of `org.tordini.flavio.Minitube` looks like this (modules build sequence is `fribidi` -> `libass` -> `libmpv`):
![Снимок экрана от 2021-10-17 19-09-15](https://user-images.githubusercontent.com/4569691/137635583-9f68ef40-00ab-4603-b456-a11d5e09062c.png)

**Comment by Erick555** [comment]
This issue is causing broken builds, see example for kodi has which tons of modules:

`eu-strip: cannot open '/srv/buildbot/worker/build-x86_64-1/build/.flatpak-builder/rofiles/rofiles-6WhSIg/files/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/debug/lib/libavahi-client.so.3.2.9.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug.debug': File name too long`

@mwleeds could you look at it if you find some time?

**Comment by wsnipex** [comment]
any news? this issue completely breaks our build

**Comment by hfiguiere** [comment]
is there some sort of ETA of when we can see this fix appear on flathub builders? It seems to be causing more and more problems.

**Comment by TingPing** [comment]
@hfiguiere Made a release https://github.com/flatpak/flatpak-builder/releases/tag/1.2.1

@barthalion can update flathub at some point.

**Comment by barthalion** [comment]
Builders will start using it once https://flathub.org/builds/#/builders/32/builds/73956 is published.

**Comment by TingPing** [comment]
Failed to publish once so I restarted it. Its now published.

**Comment by hfiguiere** [comment]
I have had success with some build that failed before, so it seems to have gotten through.

Thanks a lot!
