### ISSUE TITLE
Missing file in the tarball

### ISSUE THREAD

**Issue by arthsmn** [flatpak/flatpak-builder#590]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak-builder/issues) for a bug that matches the one I want to file, without success.

### flatpak-builder version

1.4.2

### Flatpak version

1.14.5

### How to reproduce

1. Try building flatpak-builder from the tarball provided (not the Github's automatic one).

### Expected Behavior

It would build just fine.

### Actual Behavior

It fails saying that the file glnx-backport-testutils.c is missing.

### Additional Information

I'm trying to update flatpak-builder in nixpkgs. I downloaded the tarball manually and checked that the file is missing. In Gnome's Gitlab, the file is there, so I think it's a problem with the creation of the tarball.

The actual PR of the update: https://github.com/NixOS/nixpkgs/pull/280152

**Comment by TingPing** [comment]
Here is a fixed tarball for now: https://github.com/flatpak/flatpak-builder/releases/download/1.4.2/flatpak-builder-1.4.2-fixed-libglnx.tar.xz

**Comment by arthsmn** [comment]
It worked! Thanks!

**Comment by smcv** [comment]
Am I correct to think that the problem was the tarball being based on an outdated `Makefile-libglnx.am`, due to not regenerating `subprojects/libglnx/Makefile-libglnx.am.inc` by re-running `autogen.sh` after updating the submodule?

I think the long term fix for this is to remove the Autotools build system (#591). A step towards that could be to release 1.5.0 and up via `meson dist` (same as Flatpak 1.15.3+), so that if anyone still needs to build with Autotools, they still can, but they will have to run `autogen.sh` themselves. Flatpak 1.15.7 is going to remove Autotools completely.

**Comment by TingPing** [comment]
> due to not regenerating subprojects/libglnx/Makefile-libglnx.am.inc by re-running autogen.sh after updating the submodule?

Bingo.

**Comment by TingPing** [comment]
>  A step towards that could be to release 1.5.0 and up via meson dist (same as Flatpak 1.15.3+), so that if anyone still needs to build with Autotools, they still can, 

I just want to get rid of it in 1.5.0 personally. I'm really not sure what platforms both

- Don't Meson available (a fairly conservative version can be used)
- Package the latest version of flatpak-builder
